### ISSUE TITLE
The Live demo not working iOS 11.4.1

### ISSUE THREAD

**Issue by nibl** [addpipe/simple-recorderjs-demo#2]
I tried the live demo today on four different browsers  under iOS 11.4.1 : mobile Safari, Firefox, Chrome, and Puffin.

I do not get the dialog requesting mic permission. On some browsers the recording button responds. Stop and pause also respond to touch but nothing else happens.

I tested the live demo on an iPod touch 6G. It is a new device. Are there perhaps some settings or permissions I have missed?

 Or is the live demo page outdated and the current source code would work? I just wanted to see the demo working before I invest any time with the code.

This is an excellent project. I have been waiting for this for several years. I hope it all works.

Cheers.

**Comment by octavn** [comment]
When recording using Safari where you in a different app like Gmail/Facebook which opened the demo link in the in app browser? 

I just tried using standalone Safari on iOS 11.4.1 on a 6S and it worked as expected.

Chrome on iOS did  no implement `getUserMedia()` so it will not work. Not sure about Firefox/Puffin.

**Comment by nibl** [comment]
I used standalone mobile Safari.

I had an idea that maybe the privacy setting permission had not been added because I had already enabled microphone and camera manually and those are two separate settings. The privacy settings list several apps I have given permission to use the microphone, but not Safari. So I disabled microphone and camera and then tried again.

Nothing happened in the live demo. Same behaviour.

However, I tried speakpipe and that caused a new page to appear  referring to a permissions dialog. But it only appeared for 0.5 seconds and then showed a page saying you did not allow access.

So there is some kind of bug with permissions on the iPod touch 6G.

Do you know how to report that to Apple?
