### ISSUE TITLE
MP3 support would be phenomenal

### ISSUE THREAD

**Issue by hopelang727** [addpipe/simple-recorderjs-demo#4]
MP3 and/or ogg vorbis  support would be phenomenal

I could pay you something to add that.

**Comment by octavn** [comment]
You can use [WebAudioRecorder.js](https://github.com/higuma/web-audio-recorder-js) to record MP3 or Vorbis in OGG. 

We've already covered the library:

- Article: https://addpipe.com/blog/using-webaudiorecorder-js-to-record-audio-on-your-website/
- Live Demo: https://addpipe.com/simple-web-audio-recorder-demo/
- Code on GitHub: https://github.com/addpipe/simple-web-audio-recorder-demo
