### ISSUE TITLE
Can I use the recorded file to send it as attachment to gmail?

### ISSUE THREAD

**Issue by sallu-tech** [addpipe/simple-recorderjs-demo#9]
My requirement is simple and straight forward. I want to record the message and send it as an attachment to gmail using PHPMailer. Is it possible and supported by this? Because I have been trying but I get an error on move_uploaded_file function of php. Immediate response would be highly appreciated. Thanks !!

**Comment by n-is-k** [comment]
Hi Sallu - did you figure this one out?

**Comment by sallu-tech** [comment]
Hello @n-is-k 
This library was kinda outdated so I am afraid I switched to another library due to my requirements.

**Comment by n-is-k** [comment]
Thanks for your response sullu-tech 

I wondered if you might be able to make any recommendations, perhaps achieving something similar to your original query. Or perhaps some more up-to-date versions of audio-recorder libraries that can upload to server/or gmail/or wherever.

**Comment by sallu-tech** [comment]
If you are using PhpMailer, then it has a built-in function
"addAttachment()" which you can use to attach any kind of attachment with
your message body.
